First pass in MicroK8s on s390x blog
evilnick/k8s-crew pull request #9
Opened 2021-09-16 14:15 UTC by ktsakalozos

2021-09-20 12:15 UTC, evilnick commented on content/en/blog/_posts/microk8s-s390x.md
> +
You should probably put your name and title at the bottom

2021-09-20 15:13 UTC, evilnick requested changes
Please add name/title. I also don't seem to have edit permissions on your PR so I can't edit it.

2021-09-25 07:40 UTC, ktsakalozos commented
> Please add name/title. I also don't seem to have edit permissions on your PR so I can't edit it.

Just added the name and affiliation on the blog. Also I think I turned on access to the maintainers.

2021-09-27 09:39 UTC, evilnick reviewed
:cake:

2021-09-27 09:39 UTC, evilnick approved these changes

2021-09-27 09:39 UTC, merged